# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/

# baseURL = "https://example.com"

baseURL = "http://localhost:1314/"
#baseURL = "https://huachengzhou.github.io/cycle/books"
title = 'Hugo Book'
theme = 'hugo-book'

